dataset:
  class: auem.data.datasets.audioset.IterableAudiosetDataset
  folds:
    train: /home/const/Projects/data/audioset/datasplits/balanced_train_segments-train-full.csv
    val: /home/const/Projects/data/audioset/datasplits/balanced_train_segments-val-full.csv
  params:
    audioset_path: /home/const/Projects/data/audioset/yt_audio/balanced_train/
    ontology: /home/const/Projects/data/audioset/ontology/ontology.json
    audio_cache_dir: /home/const/Projects/data/audioset/feature_cache/
    streamer_settings:
      n_frames: 10
      n_target_frames: 1
      n_active: 2
      rate: 3
