dataset:
  class: auem.data.datasets.AudiosetDataset
  folds:
    train: /home/const/Projects/data/audioset/datasplits/balanced_train_segments-train-dev-2k.csv
    val: /home/const/Projects/data/audioset/datasplits/balanced_train_segments-val-dev-2k.csv
  params:
    audioset_path: /home/const/Projects/data/audioset/yt_audio/balanced_train/
    ontology: /home/const/Projects/data/audioset/ontology/ontology.json
    audio_cache_dir: /home/const/Projects/data/audioset/feature_cache/
