transform:
  class: torchaudio.transforms.MelSpectrogram
  params:
    sample_rate: 44100
    n_fft: 1024
    win_length: 1024
    hop_length: 512
    f_min: 0.0
    # f_max: None
    pad: 0
    n_mels: 128
