defaults:
  - hydra/job_logging: info
  - datasets: audioset-iterable
  - dataloaders: standard
  - transforms: melspec
  - models: resnet18
  - optims: adam
  - criterions: bceloss
  - schedulers: cyclelr

eval: True
epochs: 20
steps: 500
checkpoint:
  embeddings:
    enabled: True
    frequency: 100
  model:
    enabled: True
    frequency: 100
validation_accuracy: True
cuda:
  enable: True
  device: "cuda"
