defaults:
  - hydra/job_logging: info
  - datasets: audioset-dev2k
  - dataloaders: standard
  - transforms: melspec
  - models: simplecnn
  - optims: adam
  - criterions: bceloss
  - schedulers: cyclelr

eval: True
epochs: 2000
checkpoint:
  embeddings:
    enabled: True
    frequency: 100
  model:
    enabled: True
    frequency: 100
cuda:
  enable: True
  device: "cuda"
