defaults:
  - hydra/job_logging: debug
  - datasets: dcase2020task1a
  - dataloaders: standard
  - models: simplenn
  - optims: adam
  - criterions: nll


eval: True
epochs: 2000
checkpoint:
  embeddings:
    enabled: True
    frequency: 100
  model:
    enabled: True
    frequency: 100
cuda:
  enabled: True
  device: "cuda"
