scheduler:
  class: torch.optim.lr_scheduler.CyclicLR
  params:
    base_lr: 0.0001
    max_lr: 0.01
    step_size_up: 2000
    step_size_down: 2000
    mode: 'triangular'
    gamma: 1.0
    scale_mode: 'cycle'
    cycle_momentum: False
    base_momentum: 0.8
    max_momentum: 0.9
    last_epoch: -1
